version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: labreport_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labreport_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/labreports
      - FHIR_BASE_URL=http://hapi.fhir.org/baseR4
      - JWT_SECRET=supersecretkey123
    depends_on:
      - mongodb
    networks:
      - healthnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labreport_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - healthnet

volumes:
  mongodb_data:

networks:
  healthnet:
    driver: bridge
